# Site settings
title: Everything.io
email: support@everything.io
description: > # this means to ignore newlines until "baseurl:"
  "A technology company"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://everything.io" # the base hostname & protocol for your site
twitter_username: everythingdotio

# Build settings
markdown: kramdown

gems:
  - "autoprefixer-rails"
  - "jekyll-assets"

sass:
  load_paths:
    - "_sass"
    - "_kickstart"
    - "_kickstart/lib-core/sass"

assets:
  sources:
    - "_assets/javascripts"
    - "_assets/stylesheets"
    - "_sass"
    - "_kickstart"
    - "_kickstart/lib-core/sass"
